unicode.mt: Script which breaks traceln
Traceback (most recent call last):
  File "/home/miea/code/monte/bin/monte", line 18, in <module>
    monte_eval(open(sys.argv[1]).read(), scope)
  File "/home/miea/code/monte/monte/runtime/load.py", line 36, in eval
    __builtin__.eval(code, mod.__dict__)
  File "5c24f25a3458437e8f39e610bc9f677b", line 3, in <module>
  File "/home/miea/code/monte/monte/runtime/trace.py", line 5, in traceln
    print x
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position
0: ordinal not in range(128)