Test chars and strings.
Strings throw a different error

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0:
ordinal not in range(128)

This is due to UTF-8 being set wrong somewhere. Should be reasonably simple to
track down in the morning -- it looks like that one wok bug.